### ISSUE TITLE
Backup hangs

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [zanglerecke/Backup-Owncloud#1]
Hello great app thanks!
Owncloud 8.1.1
latest version of your app.

When backing up the small backup screen keeps showing and doesnt go away, only when i refresh, the backup does happen, any thoughts?

Thanks, kind regards,

Ezra

**Comment by zanglerecke** [comment]
i just have less time rigth now, but i ran it on my one... i will look for it as soon as i have some time left ;)

thanks

**Comment by zanglerecke** [comment]
i just did successfully a manual backup and evrything worked as expected.

what backup screen do you mean?
